### ISSUE TITLE
Question about add/edit product page - filling data on page then page is not relevant

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop-specs#100]
What happens if I start filling data for a tab then make this tab irrelevant ?

Example:
- I create a new Virtual product
- I start filling the "Virtual product" tab
- then I modify the product type from "virtual" to "standard"

What happens to the data I filled in "Virtual product" tab ?

**Comment by marionf** [comment]
If I filled something in virtual tab and I go back to standard (whether I saved or not), then what I had filled is kept for the fields which are displayed again in the quantity tab

**Comment by matks** [comment]
Will this answer go into the spec doc 😊?

**Comment by marionf** [comment]
Yes, it's done here: https://github.com/PrestaShop/prestashop-specs/commit/45c40af4b9a6126a6ea3f351851c79207d0e2bbe

**Comment by matks** [comment]
Then we can close the issue 👍
