### ISSUE TITLE
Question about add/edit product page - attachments

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop-specs#105]
On "Options" tab we can add files to product, we call them "attachments".

It seems I can use checkboxes on these files but I dont see what I can do to them.
So it seems
- I cannot edit a file
- I cannot delete a file
- no bulk actions available
... I can just add more files

Do you confirm ? @marionf 
<img width="842" alt="Capture d’écran 2020-03-16 à 17 44 45" src="https://user-images.githubusercontent.com/3830050/76780760-d7751880-67ad-11ea-8e22-dd7ea2b99422.png">

**Comment by marionf** [comment]
@matks 

Yes, the checkbox is useless, there is an issue to remove it: https://github.com/PrestaShop/PrestaShop/issues/9790
