### ISSUE TITLE
Possibility for the customer to purshase more items from 'free gift'

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/prestashop-specs#109]
Hello guys,
Please to integrate this info into specs the way you see fit.

When a cart rule is created with a "free gift" action, the product selected as gift is gifted only one time. Consequently, the customer can pay/purchase additional quantity for this product.  In other words, customer, can add more items from free gift to cart and he will be charged the additional items. The possible wanted quantity has to be:

minimal quantity < possible quantity <= available quantity

This is discussed in issue raised by @ebaurau and managed by @khouloudbelguith .
link: https://github.com/PrestaShop/PrestaShop/issues/18129

**Comment by LouiseBonnard** [comment]
HI @arouiadib, thanks for your issue, we will address it as soon as the cart rule page will be specified.

**Comment by LouiseBonnard** [comment]
Hello again @arouiadib, I have just created the specification based on your issue. I'm looking forward to your review, let me know if it sounds clear enough to you: https://github.com/PrestaShop/prestashop-specs/pull/151, thank you very much!

**Comment by arouiadib** [comment]
@LouiseBonnard , 
Very clear! 

I am happy that we have today a link to give to merchants (when they are confused about this behaviour and think it is a bug). It will also allow less work for support team explaining and re-explaining.

I think that also future devs will love to have specs.
I long to come back here and write more trials...Thank you @LouiseBonnard for your usual encouragements.
