### ISSUE TITLE
Multistore behavior for Product page

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop-specs#112]
Hi @marionf the Product add/edit page mentions
```
The first step is to detail the behavior of each field per tab when creating / editing a product.
The second step of this document is to detail the type of each fields and error messages per tab.
The third step is to detail the multistore behavior.
```
https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md

When can we get the 3rd step ? 😄it might bring some technical challenges that I'd like to explore early

Also it would be great, but it's a lot of work to know, for each field/input in Product page, how it behaves with multistore.
- For things like "product name" it's easy 😄
- But some fields are not multi-store compatible I guess (for example "product type": a product cannot be virtual for shop 1 and not-virtual for shop 2)
- Some inputs might have specific behaviors: what about specific prices ? can they be linked to multiple shops ? what about categories ? can you "link product A with category B on multiple shops" ?
- Some fields will have increased complexity because they involve lot of items: for example image upload : can you share images between multishops ? when I delete one image for 1 shop, should I really delete it or should I keep it but "unlink" it for this shop (and keep it for other shops). Actually I don't even know if this is possible

The very best would be, for each input, to tell us
- current multishop behavior (it can be used in multishop / it cannot be used / it's broken)
- expected multishop behavior

**Comment by marionf** [comment]
Hey @matks 

I am working on this, but it will take a lot of time

**Comment by matks** [comment]
> Hey @matks
> 
> I am working on this, but it will take a lot of time

I will wait as long as it takes 😊

**Comment by marionf** [comment]
Edit: Follwing the meeting of this morning, we have to decide if we migrate the multistore of the product page ISO with current behavior (it means without checkboxes) or if we restore the checkboxes during the migration. According to this decision, I will write the specs with current multistore behavior or expected multishop behavior

**Comment by marionf** [comment]
The product page will be migrated in 1.7.8 ISO, so without checkboxes
The specs to make the product page compliant with the multistore are not ready and this will require specific interviews

**Comment by marionf** [comment]
I close this issue as @MatShir worked on this topic
