### ISSUE TITLE
Remarks on Product specs

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/prestashop-specs#171]
List of missing or different behaviors between specs and product page on 1.7.7. Note that some of them are probably bugs.

- [x] 1. In [Product Listing - Link part](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-listing.md#links) : 1 missing link : 

* Product image: Open the product in the same browser tab and on the basic settings tab. If there is no product image, there is no link

=> Fixed by #177

- [x] 2. In [Product Creation/Edit - Elements in all tabs](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#elements-in-all-tabs-epic) : 5 missing behaviors (or bug on actual Product page ?)  : 

* Product list : When the quantity of a product is at 0 or negative, it's displayed on a red background
![spec product list no quantity](https://user-images.githubusercontent.com/55688534/98650432-2cffc600-2339-11eb-9ca5-cce124eb2697.png)
* Duplicate : Quantity (or combination quantity) is not duplicated (set to 0) => Bug , will be added during migration
* Duplicate : Quantity tab > Stock location is not duplicated (new product has an empty field) => Bug , will be added during migration
* Duplicate : Shipping tab > Available carriers is not duplicated (no carrier are selected after that) => Bug , will be added during migration
* Duplicate : Options tab > Files are not duplicated (the files are unchecked) => Bug , will be added during migration

3. In [Product Creation/Edit - Basic settings tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#basic-settings-tab-epic), 2 suggestions, 2 missing infos and 3 issues : 

- [x] * Search category and Select category could be merged into only one point, since it's the same process.
- [x] * Parent of the category : If two categories have the same name, only the first one is displayed : All should be displayed (with ID in front ?)
* Image upload : If I upload several images and one of them is too large (Advanced Parameters > Administration > Upload Quota), this image is not uploaded but there is no error message.
* Image upload : When uploading the following picture, I have an error. I uploaded another image, approximately same file size, but squared, so maybe it's the width of the image that triggers this bug.
File uploaded : 
https://upload.wikimedia.org/wikipedia/commons/e/ea/Sydney_Harbour_Bridge_night.jpg
Error : 
https://drive.google.com/file/d/1OYrPhmUz80tF7AiRh2YZZB4MmLebQPYJ/view?usp=sharing
* Delete [image] : What happens when we delete the cover image ?
* Add a brand : Maybe add that only one brand can be added ?
* Pack search for a product : Maybe add that each combination of a product with combination can be added ?

4. In [Product Creation/Edit - Virtual product tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#virtual-product-tab-epic) : 1 missing info
* In associated files, for Expiration date and Number of days fields : What happens if both fields are filled ? The first deadline reached is the one taken into account, or the last one ?
* Expiration date : What happens if product is buy after expiration date ?

5. In [Product Creation/Edit - Combinations tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#combinations-tab-epic) : 2 suggestions 3 questions 1 missing info
* "ISBN" field : On actual PS version, dash character is also accepted in this field (and it makes sense since ISBN are sometimes displayed with a dash in it, for example the « ISBN-13 » field on this Amazon book has a dash in it : https://www.amazon.com/gestion-projets-pour-nuls/dp/2754019847
=>  This is also applicable to ISBN field in [Product Creation/Edit - Options tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#options-tab-epic)
* In "Bulk Action" and "Edit Combinations" : "Impact on weight" field : What happens when the impact on weight makes the product weight to be negative ? (should be 0, but it might be useful to add it to the spec, in order to avoid any unwanted behaviour)
* In Bulk Action : "Impact on price (tax excl.)" and "Impact on price (tax incl.)" : The line "When you change it, the same field in pricing tab is also updated." is false (probably a bad copy/paste)
* "MPN" field : The MPN is displayed in product details tab of the front-office and change accordingly to the selected combination.
* "Images" field : What is a « default » image ? And can we still select many images for each combination (this is not specified)

6. In [Product Creation/Edit - Shipping tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#shipping-tab-epic) : 2 missing info
* Additional shipping fees : Is this fee tax excluded ? And if there is a "Free shipping" voucher, is this shipping fee also free ?
* Available carriers : What is the expected behavior when all carriers are unchecked ?

7. In [Product Creation/Edit - Pricing tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#pricing-tab-epic) : 2 questions, 1 issue, 1 missing info
- [x] I'm not sure to really understand how the "Price ecotax included" works : It appears the user can fill this field, but shouldn't it only be calculated using the "Price" (without ecotax) and the "Ecotax" fields ? Or does the "Price ecotax included" replace the standard "Price" field when Ecotax option is enabled ?
Or do these fields replace the previous ones when Ecotax is enabled ?
* In "Display the "On sale!" flag on the product page, and on product listings" : The specification should use the English display instead of the French one (« ON SALE! »), or just « it displays a promotional banner » .
* "Retail price per unit (tax excl.)" and "Unity field" are displayed in FO only if both fields are filled.
* For "Priorities" choice : What happens if, for example, all priorities are the same (« Shop » for all 4 dropdown) : Which specific price is applied first ?

8. In [Product Creation/Edit - SEO tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#seo-tab-epic) : 1 question and 1 issue
* I do not understand these two lines (the action seems to be the same, but the result is different ?)
> If I edit the product name and if there is nothing in the meta title field, it’s displayed directly in the preview.
If I change the name of the product, the preview will not change until the meta title field is complete.

* "Indexation by search engines" : This field is in duplicate

9. In [Product Creation/Edit - Options tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#options-tab-epic) : 1 question 4 suggestions 1 missing info
* "Show price" field : The « volume discount » block is still displayed when « Show price » is disabled : Is this OK or should it be hidden too ?
* "ISBN" field : On actual PS version, dash character is also accepted in this field (and it makes sense since ISBN are sometimes displayed with a dash in it, for example the « ISBN-13 » field on this Amazon book has a dash in it : https://www.amazon.com/gestion-projets-pour-nuls/dp/2754019847
=>  This is also applicable to ISBN field in [Product Creation/Edit - Combinations tab](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/products/catalog-products-add-edit.md#combinations-tab-epic)
* ISBN, EAN, UPC and MPN fields are not displayed in FO, excepted when it’s added on combinations tab. This behavior seems weird to me : It should (IMHO) always be displayed when filled (no matter what type of product we are dealing with). If some on these fields are filled in Combinations Tab AND in Options Tab, the fields in Combinations Tab should be displayed on FO.
* "Label" field in customization : This field is required, I think it should be specified
* "Add" field in "Attach a new file" : «  If there is only 1 file and not checked » should be «  If there is no file checked »
* "Information message about suppliers" : This functionality does not exist anymore so this phrase should not be displayed : « “When using the advanced stock management tool (see Shop Parameters > Products settings), the values you define (price, references) will be used in supply orders.”

**Comment by marionf** [comment]
> I'm not sure to really understand how the "Price ecotax included" works : It appears the user can fill this field, but shouldn't it only be calculated using the "Price" (without ecotax) and the "Ecotax" fields ? Or does the "Price ecotax included" replace the standard "Price" field when Ecotax option is enabled ?
Or do these fields replace the previous ones when Ecotax is enabled ?

@Robin-Fischer-PS 
It's the same field as the standard price field, we just add an information in the label : "ecotax included" when the ecotax is enabled  in International > Taxes to make the merchant understand that he must enter the price with the ecotax included in this field.

I edited the specs [here](https://github.com/PrestaShop/prestashop-specs/pull/180/commits/ea2515c4d8c847a6169a62451b6a42bb302b73b5), tell me if it's more clear :)

**Comment by marionf** [comment]
I close this issue as comments have been adressed.
